"""LLM runner abstractions for the engineering-agent participants pool."""

from .base import (
    AgentRequest,
    AgentResponse,
    AgentRunner,
    RunnerCapability,
    RunnerError,
    RunnerHooks,
    RunnerStatus,
    RunnerUnavailableError,
)
from .claude_code import ClaudeCodeRunner
from .codex import CodexRunner
from .gemini import GeminiRunner
from .github_copilot import GitHubCopilotRunner
from .ollama import OllamaRunner
from .bootstrap import (
    ENV_OLLAMA_ENDPOINT,
    ENV_PROVIDERS,
    RunnerWiringEntry,
    RunnerWiringTrace,
    build_role_runner_candidates,
    build_role_runner_dispatch_from_env,
    install_engineering_role_runner_dispatch,
)
from .role_runner import (
    DEFAULT_PROVIDER_PRIORITY,
    DeterministicRoleRunner,
    PROVIDER_CLAUDE,
    PROVIDER_CODEX,
    PROVIDER_DETERMINISTIC,
    PROVIDER_OLLAMA,
    RoleRunner,
    RoleRunnerInput,
    RoleRunnerOutput,
    STATUS_ERROR,
    STATUS_FALLBACK,
    STATUS_INACTIVE_ROLE,
    STATUS_OK,
    STATUS_UNAVAILABLE,
    build_audit_record,
    build_role_runner_dispatcher,
    claude_role_runner,
    codex_role_runner,
    is_role_active_for_research,
    ollama_role_runner,
)

__all__ = [
    "AgentRequest",
    "AgentResponse",
    "AgentRunner",
    "ClaudeCodeRunner",
    "CodexRunner",
    "DEFAULT_PROVIDER_PRIORITY",
    "DeterministicRoleRunner",
    "ENV_OLLAMA_ENDPOINT",
    "ENV_PROVIDERS",
    "GeminiRunner",
    "GitHubCopilotRunner",
    "OllamaRunner",
    "PROVIDER_CLAUDE",
    "PROVIDER_CODEX",
    "PROVIDER_DETERMINISTIC",
    "PROVIDER_OLLAMA",
    "RoleRunner",
    "RoleRunnerInput",
    "RoleRunnerOutput",
    "RunnerCapability",
    "RunnerError",
    "RunnerHooks",
    "RunnerStatus",
    "RunnerUnavailableError",
    "RunnerWiringEntry",
    "RunnerWiringTrace",
    "STATUS_ERROR",
    "STATUS_FALLBACK",
    "STATUS_INACTIVE_ROLE",
    "STATUS_OK",
    "STATUS_UNAVAILABLE",
    "build_audit_record",
    "build_role_runner_candidates",
    "build_role_runner_dispatch_from_env",
    "build_role_runner_dispatcher",
    "claude_role_runner",
    "codex_role_runner",
    "install_engineering_role_runner_dispatch",
    "is_role_active_for_research",
    "ollama_role_runner",
]
