"""SQLite-backed job queue for the always-on engineering runtime.

This module is **additive**: no existing code path consumes it yet.
Phase A-M1 lays the foundation (schema + state machine + lease-based
``pick``) so subsequent migrations (A-M3 research worker, A-M4 role
worker) can move dispatch off the in-process gateway and onto a queue
without rewriting consumers each time.

Public surface:

- :class:`JobState` — 11-state lifecycle enum
- :class:`Job` — frozen dataclass mirroring one ``job_queue`` row
- :class:`JobQueue` — CRUD facade around the SQLite tables
- :data:`STATE_TRANSITIONS` — allowed transitions, validated on update

The queue lives in the same SQLite file as :mod:`storage.local_cache`
(``.cache/yule/cache.sqlite3`` by default, overridable via
``YULE_CACHE_DB_PATH``) so cross-table consistency stays under one
file lock + one WAL.
"""

from .approval_reply import (
    ApprovalIntent,
    ApprovalReplyOutcome,
    approval_to_obsidian_write_request,
    find_replyable_approval,
    handle_approval_reply,
    parse_approval_intent,
)
from .autonomy_lock import (
    AutonomyLock,
    AutonomyLockRegistry,
    branch_scope,
    coding_job_scope,
    session_scope,
)
from .autonomy_producer import (
    AUTONOMY_PRODUCER_HOLDER,
    AutonomyDispatch,
    AutonomyProducer,
    AutonomyProducerReport,
    AutonomyTickContext,
    DispatchOutcome,
    PRODUCER_TICK_LOCK_TTL_SECONDS,
)
from .approval_worker import (
    APPROVAL_KIND_ENGINEERING_WRITE,
    APPROVAL_KIND_OBSIDIAN_WRITE,
    APPROVAL_KIND_RESEARCH_PROMOTION,
    ApprovalChannelResolver,
    ApprovalJobOutcome,
    ApprovalPostFn,
    ApprovalRequest,
    ApprovalWorker,
    JOB_TYPE_APPROVAL_POST,
    SERVICE_ID_APPROVAL_WORKER,
    SKIPPED_APPROVAL_CHANNEL_UNSET,
    SKIPPED_CLAIMED_BY_OTHER_WORKER,
    SKIPPED_DUPLICATE,
    env_approval_channel_resolver,
    render_approval_request,
)
from .claude_decision_seam import (
    ClaudeDecisionPort,
    DECISION_KIND_DISCUSSION_FOLLOWUP,
    DECISION_KIND_NEXT_TASK,
    DECISION_KIND_RETRY_GUARD,
    DecisionRequest,
    DecisionResponse,
    DeterministicDecisionPort,
    compose_decision_port,
)
from .completion_funnel import (
    COMPLETION_FUNNEL_EXTRA_KEY,
    CompletionFunnelOutcome,
    FunnelDecision,
    build_completion_funnel,
    funnel_completion,
)
from .discussion_followup import (
    DISCUSSION_FOLLOWUP_EXTRA_KEY,
    DISCUSSION_FOLLOWUP_KIND_RESEARCH,
    DISCUSSION_FOLLOWUP_KIND_ROLE_TAKE,
    DiscussionFollowupDispatcher,
    DiscussionFollowupOutcome,
    build_discussion_followup_dispatcher,
    dispatch_discussion_followup,
    stamp_followup_marker,
)
from .ci_retry_orchestrator import (
    CIRetryDecision,
    CIStatusFetcher,
    GithubAppCheckRunFetcher,
    SESSION_EXTRA_PROGRESS_KEY as CODING_EXECUTOR_PROGRESS_EXTRA_KEY,
    orchestrate_ci_retry,
)
from .coding_execute_dispatcher import (
    DispatchedCodingJob,
    ENV_DEFAULT_BASE_BRANCH as ENV_CODING_EXECUTOR_DEFAULT_BASE_BRANCH,
    ENV_DEFAULT_REPO as ENV_CODING_EXECUTOR_DEFAULT_REPO,
    ENV_DRY_RUN as ENV_CODING_EXECUTOR_DRY_RUN,
    ReadyCodingJob,
    SESSION_EXTRA_DISPATCH_KEY as CODING_EXECUTOR_DISPATCH_EXTRA_KEY,
    WorkflowSessionState,
    build_coding_execute_request,
    dispatch_ready_coding_jobs,
    iter_ready_coding_jobs,
)
from .coding_execute_progress import (
    ProgressEntry,
    ProgressOutcome,
    TASK_LOG_NOTE_KIND,
    make_github_pr_comment_fn,
    record_coding_execute_progress,
    render_progress_markdown,
)
from .coding_executor_worker import (
    CodingExecuteOutcome,
    CodingExecuteRequest,
    CodingExecutorWorker,
    JOB_TYPE_CODING_EXECUTE,
    SERVICE_ID_CODING_EXECUTOR,
)
from .github_work_order import (
    APPROVAL_KIND_GITHUB_WORK_ORDER,
    CodingIntent,
    GitHubWorkOrder,
    GitHubWorkOrderDispatchOutcome,
    GitHubWorkOrderProposal,
    JOB_TYPE_GITHUB_WORK_ORDER,
    SERVICE_ID_GITHUB_WORK_ORDER,
    detect_coding_intent,
    dispatch_github_work_order,
    find_active_work_order,
)
from .heartbeat import (
    DEFAULT_HEARTBEAT_DEADLINE_SECONDS,
    DEFAULT_HEARTBEAT_INTERVAL_SECONDS,
    HeartbeatRecord,
    HeartbeatStore,
    SupervisorSweepReport,
    run_supervisor_sweep,
)
from .obsidian_writer_worker import (
    JOB_TYPE_OBSIDIAN_WRITE,
    NOTE_KIND_DECISION,
    NOTE_KIND_KNOWLEDGE,
    NOTE_KIND_MEETING,
    NOTE_KIND_RESEARCH,
    NOTE_KIND_WORK_REPORT,
    ObsidianRenderError,
    ObsidianWriteJobOutcome,
    ObsidianWriteRequest,
    ObsidianWriterWorker,
    RenderNoteFn,
    SERVICE_ID_OBSIDIAN_WRITER,
    SKIPPED_APPROVAL_REQUIRED,
    SKIPPED_VAULT_UNAVAILABLE,
    VaultRootResolver,
    WriteNoteFn,
    default_render_fn,
    default_vault_root_resolver,
    default_write_fn,
)
from .research_worker import (
    JOB_TYPE_RESEARCH_COLLECT,
    SERVICE_ID_RESEARCH_WORKER,
    ResearchJobOutcome,
    ResearchWorker,
    RunnerCallable,
)
from .role_take_worker import (
    JOB_TYPE_ROLE_TAKE,
    KIND_OPEN,
    KIND_SYNTHESIS,
    KIND_TURN,
    RoleTakeJobOutcome,
    RoleTakeRunner,
    RoleTakeWorker,
    SERVICE_ID_ROLE_WORKER_PREFIX,
    service_id_for_role,
)
from .state_machine import (
    JobState,
    STATE_TRANSITIONS,
    TERMINAL_STATES,
    is_terminal,
    validate_transition,
)
from .store import (
    Job,
    JobQueue,
    JobQueueError,
    QueueDatabaseError,
)


__all__ = (
    "AUTONOMY_PRODUCER_HOLDER",
    "APPROVAL_KIND_ENGINEERING_WRITE",
    "AutonomyDispatch",
    "AutonomyLock",
    "AutonomyLockRegistry",
    "AutonomyProducer",
    "AutonomyProducerReport",
    "AutonomyTickContext",
    "DispatchOutcome",
    "PRODUCER_TICK_LOCK_TTL_SECONDS",
    "ClaudeDecisionPort",
    "DECISION_KIND_DISCUSSION_FOLLOWUP",
    "DECISION_KIND_NEXT_TASK",
    "DECISION_KIND_RETRY_GUARD",
    "DecisionRequest",
    "DecisionResponse",
    "DeterministicDecisionPort",
    "compose_decision_port",
    "COMPLETION_FUNNEL_EXTRA_KEY",
    "CompletionFunnelOutcome",
    "DISCUSSION_FOLLOWUP_EXTRA_KEY",
    "DISCUSSION_FOLLOWUP_KIND_RESEARCH",
    "DISCUSSION_FOLLOWUP_KIND_ROLE_TAKE",
    "DiscussionFollowupDispatcher",
    "DiscussionFollowupOutcome",
    "FunnelDecision",
    "branch_scope",
    "build_completion_funnel",
    "build_discussion_followup_dispatcher",
    "coding_job_scope",
    "dispatch_discussion_followup",
    "funnel_completion",
    "session_scope",
    "stamp_followup_marker",
    "CIRetryDecision",
    "CIStatusFetcher",
    "CODING_EXECUTOR_DISPATCH_EXTRA_KEY",
    "CODING_EXECUTOR_PROGRESS_EXTRA_KEY",
    "CodingExecuteOutcome",
    "CodingExecuteRequest",
    "CodingExecutorWorker",
    "DispatchedCodingJob",
    "ENV_CODING_EXECUTOR_DEFAULT_BASE_BRANCH",
    "ENV_CODING_EXECUTOR_DEFAULT_REPO",
    "ENV_CODING_EXECUTOR_DRY_RUN",
    "GithubAppCheckRunFetcher",
    "JOB_TYPE_CODING_EXECUTE",
    "ProgressEntry",
    "ProgressOutcome",
    "ReadyCodingJob",
    "SERVICE_ID_CODING_EXECUTOR",
    "TASK_LOG_NOTE_KIND",
    "WorkflowSessionState",
    "build_coding_execute_request",
    "dispatch_ready_coding_jobs",
    "iter_ready_coding_jobs",
    "make_github_pr_comment_fn",
    "orchestrate_ci_retry",
    "record_coding_execute_progress",
    "render_progress_markdown",
    "APPROVAL_KIND_GITHUB_WORK_ORDER",
    "APPROVAL_KIND_OBSIDIAN_WRITE",
    "APPROVAL_KIND_RESEARCH_PROMOTION",
    "ApprovalChannelResolver",
    "ApprovalIntent",
    "ApprovalJobOutcome",
    "ApprovalPostFn",
    "ApprovalReplyOutcome",
    "ApprovalRequest",
    "ApprovalWorker",
    "CodingIntent",
    "DEFAULT_HEARTBEAT_DEADLINE_SECONDS",
    "DEFAULT_HEARTBEAT_INTERVAL_SECONDS",
    "GitHubWorkOrder",
    "GitHubWorkOrderDispatchOutcome",
    "GitHubWorkOrderProposal",
    "HeartbeatRecord",
    "HeartbeatStore",
    "JOB_TYPE_APPROVAL_POST",
    "JOB_TYPE_GITHUB_WORK_ORDER",
    "JOB_TYPE_OBSIDIAN_WRITE",
    "JOB_TYPE_RESEARCH_COLLECT",
    "JOB_TYPE_ROLE_TAKE",
    "Job",
    "JobQueue",
    "JobQueueError",
    "JobState",
    "KIND_OPEN",
    "KIND_SYNTHESIS",
    "KIND_TURN",
    "NOTE_KIND_DECISION",
    "NOTE_KIND_KNOWLEDGE",
    "NOTE_KIND_MEETING",
    "NOTE_KIND_RESEARCH",
    "NOTE_KIND_WORK_REPORT",
    "ObsidianRenderError",
    "ObsidianWriteJobOutcome",
    "ObsidianWriteRequest",
    "ObsidianWriterWorker",
    "QueueDatabaseError",
    "RenderNoteFn",
    "ResearchJobOutcome",
    "ResearchWorker",
    "RoleTakeJobOutcome",
    "RoleTakeRunner",
    "RoleTakeWorker",
    "RunnerCallable",
    "SERVICE_ID_APPROVAL_WORKER",
    "SERVICE_ID_GITHUB_WORK_ORDER",
    "SERVICE_ID_OBSIDIAN_WRITER",
    "SERVICE_ID_RESEARCH_WORKER",
    "SERVICE_ID_ROLE_WORKER_PREFIX",
    "SKIPPED_APPROVAL_CHANNEL_UNSET",
    "SKIPPED_APPROVAL_REQUIRED",
    "SKIPPED_CLAIMED_BY_OTHER_WORKER",
    "SKIPPED_DUPLICATE",
    "SKIPPED_VAULT_UNAVAILABLE",
    "STATE_TRANSITIONS",
    "SupervisorSweepReport",
    "TERMINAL_STATES",
    "VaultRootResolver",
    "WriteNoteFn",
    "default_render_fn",
    "default_vault_root_resolver",
    "default_write_fn",
    "detect_coding_intent",
    "dispatch_github_work_order",
    "env_approval_channel_resolver",
    "find_active_work_order",
    "is_terminal",
    "render_approval_request",
    "run_supervisor_sweep",
    "service_id_for_role",
    "validate_transition",
)
