#!/usr/bin/env python3
"""Project the registry SSoT onto harness artifacts (issue #185).

Single source of truth:
  * ``agents/grants/slash-command-grants.json`` (grant table)
  * ``agents/<agent>/skills/<id>.md`` (registry skill specs)

Generated (DO NOT hand-edit):
  * ``.claude/skills/<id>/SKILL.md``      — Claude Code project skills
  * ``.agents/skills/<id>/SKILL.md``      — Codex project skills
  * ``.claude-plugin/plugin.json``        — Claude Code plugin manifest
  * ``.codex-plugin/plugin.json``         — Codex plugin manifest

The output is deterministic (sorted, no timestamps) so a drift-guard test
(``tests/agents/test_harness_projection.py``) can re-run ``--check`` and
fail if the committed artifacts diverge from the SSoT.

Usage:
  python3 scripts/sync_harness_skills.py            # write artifacts
  python3 scripts/sync_harness_skills.py --check     # exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "apps" / "engineering-agent" / "src"))

from yule_engineering.agents.harness import GrantTable, load_grant_table  # noqa: E402

PLUGIN_NAME = "yule-agent-commands"
PLUGIN_VERSION = "0.1.0"
PLUGIN_DESC = (
    "Yule 부서 에이전트의 슬래시 명령어 + 스킬 번들 (생성물). "
    "SSoT 는 agents/grants/slash-command-grants.json + 레지스트리 markdown."
)
GENERATED_MARKER = (
    "<!-- GENERATED by scripts/sync_harness_skills.py. DO NOT EDIT. "
    "SSoT: {spec} + agents/grants/slash-command-grants.json -->"
)


def _granted_departments(table: GrantTable, skill_id: str) -> List[Tuple[str, str]]:
    """Sorted [(department, autonomy)] that have *skill_id* granted."""

    out: List[Tuple[str, str]] = []
    for dept_id in sorted(table.departments):
        eff = table.effective_grants(dept_id)
        if eff is None:
            continue
        for g in eff.skills:
            if g.skill == skill_id:
                out.append((dept_id, g.autonomy))
    return out


# Projection target registry — the single place that maps a vendor-neutral
# `harness` token (from a skill's grant spec) to its harness artifact layout.
# Adding a new projection target (e.g. Gemini) is a registry entry + a generator
# branch; see docs/provider-capability-matrix.md "Gemini projection". Unknown
# targets are skipped explicitly rather than silently mislabeled.
HARNESS_TARGETS: Dict[str, Dict[str, str]] = {
    "claude": {"label": "Claude Code", "skills_dir": ".claude/skills", "plugin_dir": ".claude-plugin"},
    "codex": {"label": "Codex", "skills_dir": ".agents/skills", "plugin_dir": ".codex-plugin"},
    # "gemini": {"label": "Gemini CLI", "skills_dir": ".gemini/commands", "plugin_dir": ".gemini-plugin"},  # 후속
}


def _render_skill_md(
    table: GrantTable, skill_id: str, *, harness: str
) -> str:
    skill = table.custom_skills[skill_id]
    grants = _granted_departments(table, skill_id)
    grant_lines = "\n".join(
        f"- `{dept}` (autonomy {autonomy})" for dept, autonomy in grants
    ) or "- (부여된 부서 없음)"
    harness_label = HARNESS_TARGETS[harness]["label"]

    frontmatter = "\n".join(
        [
            "---",
            f"name: {skill_id}",
            f"description: {skill.purpose}",
            "---",
        ]
    )
    body = "\n".join(
        [
            GENERATED_MARKER.format(spec=skill.spec),
            "",
            f"# {skill_id} ({harness_label})",
            "",
            f"**Canonical spec (SSoT):** `{skill.spec}`",
            "",
            "이 파일은 레지스트리 markdown spec 의 harness 투영물이다. 전체 워크플로우 /"
            " 하드레일 / 입출력 계약은 위 SSoT 를 읽는다 (progressive disclosure).",
            "",
            f"- 목적: {skill.purpose}",
            f"- 기본 autonomy: {skill.default_autonomy}",
            f"- harness: {', '.join(skill.harness)}",
            "",
            "## 부여된 부서 (grant table)",
            "",
            grant_lines,
            "",
            "## 사용",
            "",
            f"`{skill.spec}` 의 How to Use 절차를 따른다. harness 디렉터리(.claude/.agents)는"
            " 생성물이므로 직접 편집하지 않는다 — 변경은 SSoT 를 고치고"
            " `scripts/sync_harness_skills.py` 를 재실행한다.",
            "",
        ]
    )
    return frontmatter + "\n\n" + body


def _plugin_manifest(table: GrantTable, *, harness: str) -> str:
    skills = sorted(
        skill_id
        for skill_id in table.custom_skills
        if harness in table.custom_skills[skill_id].harness
    )
    manifest = {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "description": PLUGIN_DESC,
        "author": {"name": "yule-studio-engineering-agent"},
        "harness": harness,
        "skills": skills,
        "skills_path": HARNESS_TARGETS[harness]["skills_dir"],
        "ssot": "agents/grants/slash-command-grants.json",
    }
    return json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def build_artifacts(table: GrantTable) -> Dict[str, str]:
    """Return {relative_path: content} for every generated artifact.

    Each skill is projected only to the harness targets it declares in its
    grant spec (``harness``), and only to *registered* targets — an unknown
    target is skipped rather than mislabeled. A plugin manifest is emitted per
    target that has at least one skill.
    """

    artifacts: Dict[str, str] = {}
    targets_with_skills: set[str] = set()
    for skill_id in sorted(table.custom_skills):
        for harness in table.custom_skills[skill_id].harness:
            target = HARNESS_TARGETS.get(harness)
            if target is None:
                continue  # unknown projection target — skip explicitly
            artifacts[f"{target['skills_dir']}/{skill_id}/SKILL.md"] = _render_skill_md(
                table, skill_id, harness=harness
            )
            targets_with_skills.add(harness)
    for harness in sorted(targets_with_skills):
        target = HARNESS_TARGETS[harness]
        artifacts[f"{target['plugin_dir']}/plugin.json"] = _plugin_manifest(
            table, harness=harness
        )
    return artifacts


def write_artifacts(repo_root: Path, artifacts: Dict[str, str]) -> List[str]:
    written: List[str] = []
    for rel, content in sorted(artifacts.items()):
        target = repo_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            written.append(rel)
    return written


def check_artifacts(repo_root: Path, artifacts: Dict[str, str]) -> List[str]:
    """Return list of drifted/missing relative paths (empty == in sync)."""

    drift: List[str] = []
    for rel, content in sorted(artifacts.items()):
        target = repo_root / rel
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            drift.append(rel)
    return drift


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed artifacts match the SSoT; exit 1 on drift",
    )
    args = parser.parse_args(argv)

    table = load_grant_table()
    problems = table.validate(repo_root=_REPO_ROOT)
    if problems:
        print("grant table invalid; refusing to project:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 2

    artifacts = build_artifacts(table)

    if args.check:
        drift = check_artifacts(_REPO_ROOT, artifacts)
        if drift:
            print("harness artifacts out of sync with SSoT:", file=sys.stderr)
            for rel in drift:
                print(f"  - {rel}", file=sys.stderr)
            print(
                "\nrun: python3 scripts/sync_harness_skills.py", file=sys.stderr
            )
            return 1
        print(f"harness artifacts in sync ({len(artifacts)} files)")
        return 0

    written = write_artifacts(_REPO_ROOT, artifacts)
    if written:
        print(f"projected {len(written)} / {len(artifacts)} artifact(s):")
        for rel in written:
            print(f"  + {rel}")
    else:
        print(f"harness artifacts already in sync ({len(artifacts)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
