#!/usr/bin/env python3
"""Project the MCP server SSoT onto per-provider connection configs (issue #185 follow-up).

Single source of truth:
  * ``integrations/mcp/<id>.json`` (vendor-neutral MCP server specs)

Generated (DO NOT hand-edit) — only for servers whose ``supports_providers``
includes that provider:
  * ``.mcp.json``                 — Claude Code project MCP config (native location)
  * ``.codex-plugin/mcp.toml``    — Codex ``[mcp_servers.<id>]`` snippet
  * ``.gemini-plugin/mcp.json``   — Gemini ``mcpServers`` snippet

Hard rails:
  * **Secret values are never emitted** — only env-var *references*
    (``${KEY}`` headers for Claude/Gemini, ``bearer_token_env_var`` for Codex).
  * Output targets are repo-local + trackable. The script never writes to HOME
    / global config (Codex/Gemini native config live in HOME — we emit a tracked
    *snippet* the operator includes, never touch ``~/.codex`` / ``~/.gemini``).
  * Deterministic (sorted, no timestamps) so a drift-guard test can re-run
    ``--check``.

Usage:
  python3 scripts/sync_mcp_projection.py            # write artifacts
  python3 scripts/sync_mcp_projection.py --check     # exit 1 on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "apps" / "engineering-agent" / "src"))

from yule_engineering.agents.harness.mcp_registry import (  # noqa: E402
    McpServer,
    load_mcp_servers,
)

_TOML_MARKER = "# GENERATED by scripts/sync_mcp_projection.py. DO NOT EDIT. SSoT: integrations/mcp/"


def _bearer_env(server: McpServer) -> str:
    if server.auth and server.auth.type == "bearer" and server.auth.env:
        return server.auth.env
    return ""


def _http_command_split(command: str):
    parts = command.split()
    return (parts[0] if parts else ""), parts[1:]


def _claude_entry(server: McpServer) -> dict:
    if server.transport == "http":
        entry: dict = {"type": "http", "url": server.url}
        env = _bearer_env(server)
        if env:
            entry["headers"] = {"Authorization": "Bearer ${" + env + "}"}
        return entry
    cmd, args = _http_command_split(server.command)
    return {"type": "stdio", "command": cmd, "args": args}


def _gemini_entry(server: McpServer) -> dict:
    if server.transport == "http":
        entry: dict = {"httpUrl": server.url}
        env = _bearer_env(server)
        if env:
            entry["headers"] = {"Authorization": "Bearer ${" + env + "}"}
        return entry
    cmd, args = _http_command_split(server.command)
    return {"command": cmd, "args": args}


def _codex_block(server: McpServer) -> str:
    lines = [f"[mcp_servers.{server.id}]"]
    if server.transport == "http":
        lines.append(f'url = "{server.url}"')
        env = _bearer_env(server)
        if env:
            lines.append(f'bearer_token_env_var = "{env}"')
    else:
        cmd, args = _http_command_split(server.command)
        lines.append(f'command = "{cmd}"')
        if args:
            lines.append("args = [" + ", ".join(f'"{a}"' for a in args) + "]")
    return "\n".join(lines)


def _mcp_servers_json(servers: List[McpServer], provider: str, entry_fn) -> str:
    obj = {
        "mcpServers": {
            s.id: entry_fn(s)
            for s in servers
            if provider in s.supports_providers
        }
    }
    return json.dumps(obj, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def build_mcp_artifacts(servers: List[McpServer]) -> Dict[str, str]:
    artifacts: Dict[str, str] = {}

    claude = _mcp_servers_json(servers, "claude", _claude_entry)
    if json.loads(claude)["mcpServers"]:
        artifacts[".mcp.json"] = claude

    gemini = _mcp_servers_json(servers, "gemini", _gemini_entry)
    if json.loads(gemini)["mcpServers"]:
        artifacts[".gemini-plugin/mcp.json"] = gemini

    codex_servers = sorted(
        (s for s in servers if "codex" in s.supports_providers), key=lambda s: s.id
    )
    if codex_servers:
        blocks = [_TOML_MARKER, ""] + [_codex_block(s) + "\n" for s in codex_servers]
        artifacts[".codex-plugin/mcp.toml"] = "\n".join(blocks)
    return artifacts


def write_artifacts(repo_root: Path, artifacts: Dict[str, str]) -> List[str]:
    written: List[str] = []
    for rel, content in sorted(artifacts.items()):
        target = repo_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            written.append(rel)
    return written


def check_artifacts(repo_root: Path, artifacts: Dict[str, str]) -> List[str]:
    drift: List[str] = []
    for rel, content in sorted(artifacts.items()):
        target = repo_root / rel
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            drift.append(rel)
    return drift


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Project MCP SSoT onto provider configs.")
    parser.add_argument("--check", action="store_true", help="exit 1 if artifacts drift")
    args = parser.parse_args(argv)

    servers = load_mcp_servers()
    artifacts = build_mcp_artifacts(servers)

    if args.check:
        drift = check_artifacts(_REPO_ROOT, artifacts)
        if drift:
            print("MCP projection drift:\n  " + "\n  ".join(drift), file=sys.stderr)
            return 1
        print(f"MCP projection in sync ({len(artifacts)} files)")
        return 0

    written = write_artifacts(_REPO_ROOT, artifacts)
    if written:
        print(f"projected {len(written)} / {len(artifacts)} MCP artifact(s):")
        for rel in written:
            print(f"  + {rel}")
    else:
        print(f"MCP projection already in sync ({len(artifacts)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
