"""Armory — the skill / loadout / weapon catalog Hephaistos forges from (PR3 breadth).

Provider-NEUTRAL by design: skills describe capability / framework / workflow, never a
vendor name (``capability_note`` carries the capability lens). Each manifest is a real
contract (summary / when_to_use / commands / verify / unsafe_boundary / signals), not a
placeholder. Coverage is honest — uncovered requests resolve shallow, never faked.

Seeded in Python (a JSON manifest loader stays a planned seam). Pure / stdlib-only.
"""

from __future__ import annotations

from typing import Dict, Optional, Tuple

from .models import (
    NEXUS_AREA,
    NEXUS_PATTERN,
    NEXUS_SNIPPET,
    NEXUS_TROUBLESHOOTING,
    LoadoutSpec,
    NexusSourceRef,
    SkillSpec,
    WeaponSpec,
)


def _area(p):
    return NexusSourceRef(NEXUS_AREA, p)


_WEAPONS = (
    WeaponSpec("openjdk", "OpenJDK", "runtime", "java -version", "brew install openjdk@21"),
    WeaponSpec("gradle", "Gradle", "tool", "gradle -v", "brew install gradle"),
    WeaponSpec("node", "Node.js", "runtime", "node --version", "brew install node"),
    WeaponSpec("npm", "npm", "tool", "npm --version", "(node 동봉)"),
    WeaponSpec("python", "Python", "runtime", "python3 --version", "brew install python@3.13"),
    WeaponSpec("uv", "uv", "tool", "uv --version", "brew install uv"),
    WeaponSpec("mysql", "MySQL", "service", "mysql --version", "brew install mysql"),
    WeaponSpec("postgres", "PostgreSQL", "service", "psql --version", "brew install postgresql"),
    WeaponSpec("redis", "Redis", "service", "redis-cli --version", "brew install redis"),
    WeaponSpec("docker", "Docker", "service", "docker --version", "https://docker.com"),
    WeaponSpec("kubectl", "kubectl", "cli", "kubectl version --client", "brew install kubectl"),
    WeaponSpec("terraform", "Terraform", "cli", "terraform version", "brew install terraform"),
    WeaponSpec("awscli", "AWS CLI", "cli", "aws --version", "brew install awscli"),
    WeaponSpec("gh", "GitHub CLI", "cli", "gh --version", "brew install gh"),
    WeaponSpec("intellij", "IntelliJ IDEA", "ide", "", "jetbrains toolbox"),
    WeaponSpec("vscode", "VS Code", "ide", "code --version", "https://code.visualstudio.com"),
)

_SKILLS = (
    # --- backend ---------------------------------------------------------
    SkillSpec("java-spring", "Java / Spring Boot", category="backend",
              domains=("backend",), languages=("java",), frameworks=("spring-boot", "spring"),
              topics=("rest", "service-layer", "transaction"),
              signals=("spring", "spring boot", "java"),
              summary="Spring Boot service/REST 설계·구현",
              when_to_use=("Java/Spring 백엔드 API·service 계층",),
              when_not_to_use=("Python/Node 백엔드",),
              rules=("controller 비즈니스 로직 금지(service 분리)", "트랜잭션 경계 service 에 명시"),
              commands=("./gradlew build", "./gradlew test"),
              verification=("./gradlew test", "./gradlew check"),
              forbidden=("승인 없는 schema/auth/deploy 변경",),
              capability_note="tool-using executor (jvm build/test)",
              related_weapons=("openjdk", "gradle"), related_loadouts=("backend-java-local",),
              related_roles=("backend-engineer",),
              nexus_refs=(_area("20-areas/backend/java-spring"),
                          NexusSourceRef(NEXUS_PATTERN, "40-patterns/backend/transaction-boundary.md"))),
    SkillSpec("kotlin-spring", "Kotlin / Spring Boot", category="backend",
              domains=("backend",), languages=("kotlin",), frameworks=("spring-boot",),
              topics=("rest", "coroutine"), signals=("kotlin",),
              summary="Kotlin + Spring Boot 백엔드",
              when_to_use=("Kotlin 기반 Spring 서비스",), when_not_to_use=("순수 Java only repo",),
              rules=("null-safety 활용", "coroutine 컨텍스트 누수 주의"),
              commands=("./gradlew build",), verification=("./gradlew test",),
              forbidden=("승인 없는 schema/deploy 변경",),
              capability_note="tool-using executor (jvm/kotlin)",
              related_weapons=("openjdk", "gradle"), related_loadouts=("backend-java-local",),
              related_roles=("backend-engineer",), nexus_refs=(_area("20-areas/backend/kotlin-spring"),)),
    SkillSpec("node-nestjs", "Node / NestJS", category="backend",
              domains=("backend",), languages=("typescript",), frameworks=("nestjs",),
              topics=("rest", "di"), signals=("nestjs", "nest", "node 백엔드"),
              summary="NestJS(Node/TS) 백엔드 모듈·DI",
              when_to_use=("Node/TS 백엔드, DI 기반 모듈",), when_not_to_use=("JVM 백엔드",),
              rules=("module/provider 경계 명확", "DTO 검증 필수"),
              commands=("npm run build", "npm test"), verification=("npm test", "npm run lint"),
              forbidden=("승인 없는 migration/deploy",),
              capability_note="tool-using executor (node)",
              related_weapons=("node", "npm"), related_loadouts=("backend-node-local",),
              related_roles=("backend-engineer",), nexus_refs=(_area("20-areas/backend/node-nestjs"),)),
    SkillSpec("python-fastapi", "Python / FastAPI", category="backend",
              domains=("backend",), languages=("python",), frameworks=("fastapi",),
              topics=("rest", "async", "rate-limit", "worker"),
              signals=("fastapi", "python 백엔드", "uvicorn"),
              summary="FastAPI(async) 백엔드 API·worker",
              when_to_use=("Python async API, background worker, rate limit",),
              when_not_to_use=("JVM/Node 백엔드",),
              rules=("pydantic 모델 검증", "async I/O 일관성", "blocking 호출 격리"),
              commands=("uv run pytest", "uvicorn app.main:app --reload"),
              verification=("pytest", "ruff check ."),
              forbidden=("승인 없는 migration/deploy",),
              capability_note="tool-using executor (python async)",
              related_weapons=("python", "uv"), related_loadouts=("backend-python-local",),
              related_roles=("backend-engineer",),
              nexus_refs=(_area("20-areas/backend/python-fastapi"),)),
    # --- frontend --------------------------------------------------------
    SkillSpec("react-typescript", "React + TypeScript", category="frontend",
              domains=("frontend",), languages=("typescript",), frameworks=("react",),
              topics=("ui", "component", "state"), signals=("react", "tsx", "컴포넌트"),
              summary="React/TS 컴포넌트·상태 설계",
              when_to_use=("React 컴포넌트/상태/타입 작업",), when_not_to_use=("서버 렌더 라우팅 전반(→ nextjs)",),
              rules=("상태 최소화·파생 계산", "any 금지(타입 명시)"),
              commands=("npm run build", "npm run lint"), verification=("npm run lint", "npm test"),
              forbidden=("디자인 토큰 임의 변경(design 승인)",),
              capability_note="ui component reasoning",
              related_weapons=("node", "npm", "vscode"), related_loadouts=("frontend-react-local",),
              related_roles=("frontend-engineer",), nexus_refs=(_area("20-areas/frontend/react-typescript"),)),
    SkillSpec("nextjs", "Next.js", category="frontend",
              domains=("frontend",), languages=("typescript",), frameworks=("nextjs", "react"),
              topics=("ui", "ssr", "routing", "layout", "spacing"),
              signals=("next.js", "nextjs", "next ", "대시보드", "레이아웃", "간격", "spacing"),
              summary="Next.js 라우팅/SSR/레이아웃",
              when_to_use=("Next.js 페이지/레이아웃/간격 개선",), when_not_to_use=("백엔드 전용",),
              rules=("server/client component 경계 명확", "layout shift 주의"),
              commands=("npm run dev", "npm run build", "npm run lint"),
              verification=("npm run build", "npm run lint"),
              forbidden=("디자인 시스템 토큰 임의 변경",),
              capability_note="ui layout reasoning",
              related_weapons=("node", "npm"), related_loadouts=("frontend-react-local", "fullstack-web-local"),
              related_roles=("frontend-engineer",), nexus_refs=(_area("20-areas/frontend/nextjs"),)),
    SkillSpec("vite-react", "Vite + React", category="frontend",
              domains=("frontend",), languages=("typescript",), frameworks=("react", "vite"),
              topics=("ui", "spa", "build"), signals=("vite",),
              summary="Vite 기반 React SPA",
              when_to_use=("가벼운 SPA, 빠른 dev 빌드",), when_not_to_use=("SSR 필요 시(→nextjs)",),
              rules=("번들 사이즈 주시",), commands=("npm run dev", "npm run build"),
              verification=("npm run build",), forbidden=("토큰 임의 변경",),
              capability_note="ui spa build", related_weapons=("node", "npm"),
              related_loadouts=("frontend-react-local",), related_roles=("frontend-engineer",)),
    # --- database --------------------------------------------------------
    SkillSpec("mysql", "MySQL", category="database",
              domains=("backend", "database"), topics=("mysql", "sql", "persistence", "transaction"),
              signals=("mysql",), summary="MySQL 스키마/쿼리/트랜잭션",
              when_to_use=("관계형 영속, 트랜잭션",), when_not_to_use=("캐시/세션(→redis)",),
              rules=("스키마 변경은 migration", "N+1 주의"),
              commands=("mysql -u root -e 'SELECT 1'",),
              verification=("mysql --version", "mysql -u root -e 'SELECT 1'"),
              forbidden=("승인 없는 schema migration", "운영 DB 직접 변경"),
              capability_note="relational store", related_weapons=("mysql",),
              related_loadouts=("backend-java-local", "backend-python-local"),
              related_roles=("backend-engineer",), nexus_refs=(_area("20-areas/backend/database/mysql"),)),
    SkillSpec("postgres", "PostgreSQL", category="database",
              domains=("backend", "database"), topics=("postgres", "sql", "persistence"),
              signals=("postgres", "postgresql", "pg "), summary="PostgreSQL 스키마/쿼리",
              when_to_use=("고급 SQL/JSONB/확장",), when_not_to_use=("캐시(→redis)",),
              rules=("migration 도구 사용", "인덱스 전략 명시"),
              commands=("psql -c 'SELECT 1'",), verification=("psql --version",),
              forbidden=("승인 없는 schema 변경",), capability_note="relational store",
              related_weapons=("postgres",), related_loadouts=("backend-python-local",),
              related_roles=("backend-engineer",), nexus_refs=(_area("20-areas/backend/database/postgres"),)),
    SkillSpec("redis", "Redis", category="database",
              domains=("backend", "database"), topics=("redis", "cache", "session", "rate-limit", "worker"),
              signals=("redis", "캐시", "rate limit"), summary="Redis 캐시/세션/rate limit",
              when_to_use=("캐시, 세션, rate limit, 큐",), when_not_to_use=("영속 관계형 데이터",),
              rules=("TTL 명시", "무효화 전략"), commands=("redis-cli ping",),
              verification=("redis-cli ping",), forbidden=("운영 redis FLUSHALL 금지",),
              capability_note="in-memory store", related_weapons=("redis",),
              related_loadouts=("backend-java-local", "backend-python-local"),
              related_roles=("backend-engineer",), nexus_refs=(_area("20-areas/backend/database/redis"),)),
    # --- infra / devops --------------------------------------------------
    SkillSpec("docker", "Docker", category="devops",
              domains=("backend", "devops"), topics=("docker", "container", "local-env"),
              signals=("docker", "compose", "container"), summary="Docker/compose 로컬·이미지",
              when_to_use=("로컬 의존(db/redis) compose, 이미지 빌드",), when_not_to_use=("프로비저닝(→terraform)",),
              rules=("local 의존은 compose",), commands=("docker compose up -d",),
              verification=("docker --version", "docker compose config"),
              forbidden=("운영 registry/container 변경",), capability_note="container runtime",
              related_weapons=("docker",), related_loadouts=("backend-java-local", "devops-cloud-local"),
              related_roles=("backend-engineer", "devops-engineer")),
    SkillSpec("kubernetes", "Kubernetes", category="devops",
              domains=("devops",), topics=("kubernetes", "k8s", "deploy", "orchestration"),
              signals=("kubernetes", "k8s", "kubectl"), summary="K8s manifest/deploy",
              when_to_use=("컨테이너 오케스트레이션, 배포 manifest",), when_not_to_use=("단일 로컬 실행",),
              rules=("resource limit 명시", "secret 은 secret 리소스"),
              commands=("kubectl apply --dry-run=client -f .",),
              verification=("kubectl version --client",),
              forbidden=("운영 cluster apply(승인+runbook)", "prod namespace 변경"),
              capability_note="orchestration", related_weapons=("kubectl", "docker"),
              related_loadouts=("devops-cloud-local",), related_roles=("devops-engineer",)),
    SkillSpec("terraform", "Terraform", category="devops",
              domains=("devops",), topics=("terraform", "iac", "deploy", "provision"),
              signals=("terraform", "iac", "프로비저닝", "배포"), summary="Terraform IaC plan",
              when_to_use=("클라우드 리소스 IaC, plan 작성",), when_not_to_use=("앱 코드",),
              rules=("plan 먼저, apply 는 승인", "state backend 명시"),
              commands=("terraform init", "terraform plan"),
              verification=("terraform validate", "terraform plan"),
              forbidden=("production apply 금지(승인 필요)", "state backend 임의 변경"),
              capability_note="infra-as-code planner", related_weapons=("terraform", "awscli"),
              related_loadouts=("devops-cloud-local",), related_roles=("devops-engineer",),
              nexus_refs=(_area("20-areas/devops/terraform"),)),
    SkillSpec("aws-ecs", "AWS ECS", category="devops",
              domains=("devops",), topics=("aws", "ecs", "deploy", "container"),
              signals=("ecs", "aws", "fargate"), summary="AWS ECS 배포 가이드",
              when_to_use=("ECS/Fargate 컨테이너 배포",), when_not_to_use=("on-prem k8s",),
              rules=("task role 최소권한", "rolling/blue-green 전략 명시"),
              commands=("aws ecs describe-services",), verification=("aws --version",),
              forbidden=("production service 직접 변경(승인)",), capability_note="cloud deploy",
              related_weapons=("awscli", "docker"), related_loadouts=("devops-cloud-local",),
              related_roles=("devops-engineer",)),
    # --- auth / security -------------------------------------------------
    SkillSpec("auth-jwt", "Auth / JWT", category="security",
              domains=("backend", "security"), topics=("auth-jwt", "auth", "jwt", "refresh-token", "security"),
              signals=("jwt", "refresh token", "토큰 인증"),
              summary="JWT access/refresh 설계",
              when_to_use=("JWT 인증, refresh 회전",), when_not_to_use=("OAuth2 위임 흐름(→oauth2)",),
              rules=("refresh 저장/만료 정책", "filter chain 순서 주의", "access/refresh 분리"),
              verification=("./gradlew test --tests '*Jwt*'",),
              forbidden=("auth 정책 임의 재작성(승인)",), capability_note="auth design",
              related_weapons=("openjdk",), related_loadouts=("backend-java-local", "security-review-local"),
              related_roles=("backend-engineer", "security-engineer"),
              nexus_refs=(NexusSourceRef(NEXUS_SNIPPET, "50-snippets/java/spring-security-jwt.md"),
                          NexusSourceRef(NEXUS_TROUBLESHOOTING, "60-troubleshooting/spring/bean-cycle-error.md"))),
    SkillSpec("oauth2", "OAuth2 / OIDC", category="security",
              domains=("security", "backend"), topics=("oauth", "oauth2", "oidc", "auth", "sso"),
              signals=("oauth", "oauth2", "oidc", "sso", "소셜 로그인"),
              summary="OAuth2/OIDC 위임 인증",
              when_to_use=("3rd-party/SSO 위임 인증",), when_not_to_use=("자체 JWT만(→auth-jwt)",),
              rules=("PKCE 사용", "state/nonce 검증", "scope 최소"),
              verification=("(흐름 수동 검증)",), forbidden=("client secret 노출",),
              capability_note="federated auth", related_loadouts=("security-review-local",),
              related_roles=("security-engineer", "backend-engineer")),
    SkillSpec("secrets-management", "Secrets Management", category="security",
              domains=("security", "devops"), topics=("secret", "vault", "kms", "env"),
              signals=("secret", "비밀키", "kms", "vault"),
              summary="secret 저장/주입 정책",
              when_to_use=("자격/비밀키 관리, env 주입",), when_not_to_use=("",),
              rules=("git tracked 파일에 secret 금지", "주입은 env/secret manager"),
              verification=("git grep -nE '(secret|password|api[_-]?key)\\s*=' || true",),
              forbidden=("secret 평문 커밋", "로그에 secret 출력"),
              capability_note="secret hygiene", related_loadouts=("security-review-local", "devops-cloud-local"),
              related_roles=("security-engineer", "devops-engineer")),
    SkillSpec("web-security-review", "Web Security Review", category="security",
              domains=("security",), topics=("security", "review", "auth", "owasp"),
              signals=("보안 점검", "security review", "취약점", "auth review", "owasp"),
              summary="웹 보안 점검(OWASP 관점)",
              when_to_use=("auth/입력검증/권한 점검, 보안 리뷰",), when_not_to_use=("active 공격/침투(승인+plan-first)",),
              rules=("입력 검증/권한 체크", "secret 하드코딩 점검", "OWASP top-10 관점"),
              verification=("(checklist 전수 점검)",),
              forbidden=("실제 exploit/active attack(plan-first, 승인 필요)",),
              capability_note="security review path", related_loadouts=("security-review-local",),
              related_roles=("security-engineer"),
              nexus_refs=(NexusSourceRef(NEXUS_PATTERN, "40-patterns/security/authz-checklist.md"),)),
    # --- ai / agent ------------------------------------------------------
    SkillSpec("openai-api", "LLM API (openai-compatible)", category="ai",
              domains=("ai",), topics=("llm", "api", "completion", "embedding"),
              signals=("llm api", "openai", "completion", "embedding", "프롬프트"),
              summary="openai-compatible LLM API 연동",
              when_to_use=("LLM 호출/임베딩, provider-neutral 연동",), when_not_to_use=("로컬 모델 학습",),
              rules=("usage/cost 추적", "키는 env"), verification=("(연결 smoke)",),
              forbidden=("키 하드코딩",),
              capability_note="llm api client (vendor-neutral: openai-compatible transport)",
              related_loadouts=("ai-agent-local",), related_roles=("ai-engineer",)),
    SkillSpec("rag-basics", "RAG Basics", category="ai",
              domains=("ai",), topics=("rag", "retrieval", "embedding", "vector"),
              signals=("rag", "retrieval", "검색 증강", "vector"),
              summary="검색 증강 생성 기초",
              when_to_use=("문서 검색+생성 파이프라인",), when_not_to_use=("단순 단발 호출",),
              rules=("chunking 전략", "retrieval eval 동반"),
              verification=("(retrieval eval 점수)",), forbidden=("",),
              capability_note="long-context reader + retrieval", related_loadouts=("ai-agent-local",),
              related_roles=("ai-engineer",)),
    SkillSpec("eval-harness", "Eval Harness", category="ai",
              domains=("ai",), topics=("eval", "benchmark", "test"),
              signals=("eval", "평가", "benchmark", "harness"),
              summary="LLM/agent 평가 harness",
              when_to_use=("출력 품질 평가, 회귀 eval",), when_not_to_use=("",),
              rules=("fixture 고정", "regression 점수 추적"),
              verification=("(eval suite 실행)",), forbidden=("eval 없이 대량 변경 push",),
              capability_note="evaluation", related_loadouts=("ai-agent-local",), related_roles=("ai-engineer",)),
    SkillSpec("agent-evaluation", "Agent Evaluation", category="ai",
              domains=("ai",), topics=("agent", "eval", "trajectory"),
              signals=("agent eval", "에이전트 평가", "trajectory"),
              summary="agent 행동/trajectory 평가",
              when_to_use=("multi-step agent 품질·안전 평가",), when_not_to_use=("단일 호출 평가(→eval-harness)",),
              rules=("safety/refusal 케이스 포함",), verification=("(trajectory eval)",),
              forbidden=("승인 없는 자율 실행 평가",), capability_note="agent evaluation",
              related_loadouts=("ai-agent-local",), related_roles=("ai-engineer",)),
    # --- design-support --------------------------------------------------
    SkillSpec("figma-read", "Figma Read", category="design-support",
              domains=("design",), topics=("figma", "design-reference"),
              signals=("figma", "피그마", "디자인 참고"),
              summary="Figma 참고(연결 시 read, 아니면 blocked)", status="partial",
              when_to_use=("Figma 레퍼런스 기반 UI 비교",), when_not_to_use=("Figma 미연결 시 raw 가정",),
              rules=("raw export 를 repo/vault 본문 복사 금지", "미연결이면 blocked 정직"),
              verification=("(Figma 연결 상태 확인)",), forbidden=("미연결인데 read 한 척",),
              capability_note="design reference reader (restricted/blocked-aware)",
              related_loadouts=("design-review-local",), related_roles=("ux-ui-designer", "design-lead")),
    SkillSpec("design-system-review", "Design System Review", category="design-support",
              domains=("design",), topics=("design-system", "tokens", "consistency", "spacing"),
              signals=("디자인 시스템", "design system", "토큰", "간격 일관성"),
              summary="디자인 시스템 일관성 점검",
              when_to_use=("토큰/간격/컴포넌트 일관성 리뷰",), when_not_to_use=("코드 구현(→frontend)",),
              rules=("토큰 기준 비교", "임의 색/간격 inline 금지"),
              verification=("(토큰 대비 점검)",), forbidden=("디자인 토큰 임의 변경(design-lead 승인)",),
              capability_note="design consistency review", related_loadouts=("design-review-local",),
              related_roles=("design-systems-designer", "design-lead")),
    SkillSpec("ux-ui-reference-pack", "UX/UI Reference Pack", category="design-support",
              domains=("design",), topics=("ux", "ui", "reference", "spacing", "layout"),
              signals=("ux", "ui 참고", "레퍼런스", "spacing", "layout"),
              summary="UX/UI 개선 레퍼런스 묶음",
              when_to_use=("UI 불편 → 레퍼런스/개선 packet",), when_not_to_use=("",),
              rules=("불편 → discomfort note → reference → packet",),
              verification=("(reference pack 생성)",), forbidden=("",),
              capability_note="design reference reader", related_loadouts=("design-review-local",),
              related_roles=("ux-ui-designer",)),
)

# loadout: why this combo (goal + recommended/optional/blocked + selection signals).
_LOADOUTS = (
    LoadoutSpec("backend-java-local", "Backend Java (local)", intended_roles=("backend-engineer",),
                required_weapons=("openjdk", "gradle", "docker"),
                optional_weapons=("mysql", "redis", "intellij", "vscode", "gh"),
                environment_assumptions=("local JDK 21", "docker for db/redis"),
                verify_commands=("java -version", "gradle -v", "docker --version"),
                goal="JVM 백엔드 API 를 로컬에서 구현·검증",
                recommended_skills=("java-spring", "auth-jwt", "mysql"),
                optional_skills=("kotlin-spring", "redis", "docker"),
                blocked_skills=("terraform", "aws-ecs"),
                default_verify_flow=("./gradlew build", "./gradlew test"),
                selection_signals=("spring", "java", "kotlin"),
                notes="JVM+db+docker — 프로비저닝/배포는 devops loadout 으로 분리"),
    LoadoutSpec("backend-python-local", "Backend Python (local)", intended_roles=("backend-engineer",),
                required_weapons=("python", "uv", "docker"),
                optional_weapons=("postgres", "redis", "vscode"),
                environment_assumptions=("python 3.13", "uv", "docker for db/redis"),
                verify_commands=("python3 --version", "uv --version", "docker --version"),
                goal="Python async 백엔드(FastAPI)·worker 로컬 구현·검증",
                recommended_skills=("python-fastapi", "redis", "postgres"),
                optional_skills=("docker", "web-security-review"),
                blocked_skills=("terraform", "aws-ecs"),
                default_verify_flow=("uv run pytest", "ruff check ."),
                selection_signals=("fastapi", "python", "uvicorn"),
                notes="async I/O 중심, db/redis 는 docker compose"),
    LoadoutSpec("backend-node-local", "Backend Node (local)", intended_roles=("backend-engineer",),
                required_weapons=("node", "npm", "docker"), optional_weapons=("postgres", "redis"),
                environment_assumptions=("node LTS",),
                verify_commands=("node --version", "npm --version"),
                goal="Node/TS(NestJS) 백엔드 로컬",
                recommended_skills=("node-nestjs", "redis"), optional_skills=("postgres",),
                blocked_skills=("terraform",), default_verify_flow=("npm test", "npm run lint"),
                selection_signals=("nestjs", "node 백엔드"), notes="DI 모듈 중심"),
    LoadoutSpec("frontend-react-local", "Frontend React (local)", intended_roles=("frontend-engineer",),
                required_weapons=("node", "npm"), optional_weapons=("vscode",),
                environment_assumptions=("node LTS",),
                verify_commands=("node --version", "npm --version"),
                goal="React/Next 프론트 로컬 UI 작업",
                recommended_skills=("react-typescript", "nextjs"),
                optional_skills=("vite-react", "design-system-review"),
                blocked_skills=("terraform", "aws-ecs"),
                default_verify_flow=("npm run build", "npm run lint"),
                selection_signals=("react", "next.js", "nextjs", "프론트", "ui", "레이아웃"),
                notes="디자인 토큰 변경은 design loadout/승인"),
    LoadoutSpec("fullstack-web-local", "Fullstack Web (local)",
                intended_roles=("frontend-engineer", "backend-engineer"),
                required_weapons=("node", "npm", "docker"), optional_weapons=("mysql", "redis"),
                environment_assumptions=("node + docker",),
                verify_commands=("node --version", "docker --version"),
                goal="프론트+백엔드 통합 로컬 개발",
                recommended_skills=("nextjs", "node-nestjs", "auth-jwt"),
                optional_skills=("redis", "mysql"), blocked_skills=("terraform",),
                default_verify_flow=("npm run build",),
                selection_signals=("fullstack", "풀스택", "프론트+백엔드"),
                notes="범위 넓음 — 작업 단위는 PM packet 으로 분할 권장"),
    LoadoutSpec("devops-cloud-local", "DevOps Cloud (local)", intended_roles=("devops-engineer",),
                required_weapons=("docker", "terraform"), optional_weapons=("kubectl", "awscli"),
                environment_assumptions=("terraform/aws cli, docker",),
                verify_commands=("terraform version", "docker --version"),
                goal="클라우드 IaC/배포 plan 작성",
                recommended_skills=("terraform", "aws-ecs", "docker"),
                optional_skills=("kubernetes", "secrets-management"),
                blocked_skills=("java-spring", "react-typescript"),
                default_verify_flow=("terraform validate", "terraform plan"),
                selection_signals=("terraform", "ecs", "kubernetes", "배포", "iac"),
                notes="apply 는 항상 승인+runbook (plan-first)"),
    LoadoutSpec("ai-agent-local", "AI Agent (local)", intended_roles=("ai-engineer",),
                required_weapons=("python", "uv"), optional_weapons=("docker",),
                environment_assumptions=("python, openai-compatible endpoint",),
                verify_commands=("python3 --version",),
                goal="LLM/agent 파이프라인·평가",
                recommended_skills=("openai-api", "rag-basics", "eval-harness"),
                optional_skills=("agent-evaluation",), blocked_skills=("terraform",),
                default_verify_flow=("(eval suite)",),
                selection_signals=("llm", "rag", "agent", "eval", "embedding"),
                notes="provider-neutral(openai-compatible), usage/cost 추적"),
    LoadoutSpec("security-review-local", "Security Review (local)", intended_roles=("security-engineer",),
                required_weapons=("gh",), optional_weapons=("docker",),
                environment_assumptions=("repo read access",),
                verify_commands=("gh --version",),
                goal="auth/보안 점검 plan-first 리뷰",
                recommended_skills=("web-security-review", "auth-jwt", "oauth2"),
                optional_skills=("secrets-management",),
                blocked_skills=("terraform", "aws-ecs"),
                default_verify_flow=("(security checklist)",),
                selection_signals=("보안", "security", "auth review", "취약점", "owasp"),
                notes="active attack 금지 — plan-first, 승인 필요"),
    LoadoutSpec("design-review-local", "Design Review (local)", intended_roles=("ux-ui-designer", "design-lead"),
                required_weapons=("vscode",), optional_weapons=(),
                environment_assumptions=("design reference(연결 시)",),
                verify_commands=(),
                goal="디자인 시스템/UX 일관성 리뷰(restricted-aware)",
                recommended_skills=("design-system-review", "ux-ui-reference-pack", "figma-read"),
                optional_skills=(), blocked_skills=("terraform", "java-spring"),
                default_verify_flow=("(토큰/레퍼런스 대비)",),
                selection_signals=("디자인", "design", "figma", "ui 참고", "디자인 시스템"),
                notes="raw design source 는 design role만, 그외 projection. Figma 미연결이면 blocked"),
)

_WEAPON_BY_ID: Dict[str, WeaponSpec] = {w.id: w for w in _WEAPONS}
_SKILL_BY_ID: Dict[str, SkillSpec] = {s.id: s for s in _SKILLS}
_LOADOUT_BY_ID: Dict[str, LoadoutSpec] = {l.id: l for l in _LOADOUTS}


def all_skills() -> Tuple[SkillSpec, ...]:
    return _SKILLS


def all_loadouts() -> Tuple[LoadoutSpec, ...]:
    return _LOADOUTS


def all_weapons() -> Tuple[WeaponSpec, ...]:
    return _WEAPONS


def skill(skill_id: str) -> Optional[SkillSpec]:
    return _SKILL_BY_ID.get(skill_id)


def loadout(loadout_id: str) -> Optional[LoadoutSpec]:
    return _LOADOUT_BY_ID.get(loadout_id)


def weapon(weapon_id: str) -> Optional[WeaponSpec]:
    return _WEAPON_BY_ID.get(weapon_id)


def categories() -> Tuple[str, ...]:
    return tuple(dict.fromkeys(s.category for s in _SKILLS if s.category))


__all__ = ("all_skills", "all_loadouts", "all_weapons", "skill", "loadout", "weapon", "categories")
